#!/usr/bin/env python2
# -*- coding: utf-8 -*-

import os
import sys
sys.path.append('/usr/lib/archivematica/archivematicaCommon')
from executeOrRunSubProcess import executeOrRun
from optparse import OptionParser


if __name__ == '__main__':
    usage = "usage: %prog <command> <args>"

    parser = OptionParser(usage=usage)
    (options, args) = parser.parse_args()

    if len(args) == 1:
        command = args.pop(0)
    elif len(args) == 2:
        # get command from first arg
        command = args.pop(0)
        arguments = args.pop(1)
        command = command + arguments
    else:
        parser.print_help()
        exit()

    exitCode, stdOut, stdError = executeOrRun("command", command, '', printing=False)

    print exitCode
    print stdOut
    print stdError
